name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      CHECMOI_CMD: "./bin/chezmoi"
    steps:
      - name: Download chezmoi binary
        run: |
          #
          # download the chezmoi binary from the URL
          #
          sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Run `chezmoi init`
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          #
          # run `chezmoi init`
          #
          "${CHECMOI_CMD}" init nakamina/dotfiles --promptString "Email address"="${EMAIL_ADDRESS}"

      - name: Run `chezmoi apply`
        env:
          DOTFILES_DEBUG: 1
        run: |
          #
          # the `age` command requires a tty, but there is no tty in the github actions.
          # Therefore, it is currnetly difficult to decrypt the files encrypted with `age` in this workflow.
          # I decided to temporarily remove the encrypted target files from chezmoi's control.
          #
          find "$(${CHECMOI_CMD} source-path)" -type f -name "encrypted_*" -exec rm -fv {} +

          #
          # run `chezmoi apply`
          #
          "${CHECMOI_CMD}" apply
