name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      CHECMOI_CMD: "./bin/chezmoi"
    steps:
      - name: Download chezmoi binary
        run: |
          #
          # download the chezmoi binary from the URL
          #
          sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Run `chezmoi init`
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          #
          # run `chezmoi init`
          #
          "${CHECMOI_CMD}" init nakamina/dotfiles --promptString "Email address"="${EMAIL_ADDRESS}"

      - name: Run chezmoi apply
        env:
          DOTFILES_DEBUG: 1
        run: |
          "${CHECMOI_CMD}" apply
