name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      CHECMOI_CMD: "./bin/chezmoi"
    steps:
      - name: Download chezmoi binary
        run: |
          #
          # download the chezmoi binary from the URL
          #
          sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Run `chezmoi init`
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        run: |
          #
          # run `chezmoi init`
          #
          "${CHECMOI_CMD}" init nakamina --promptString "Email address"="${EMAIL_ADDRESS}"

      # - name: Run chezmoi apply
      #   env:
      #     DOTFILES_DEBUG: 1
      #   run: |
      #     cmd="$(curl -fsLS get.chezmoi.io)"
      #     find . -type f -name "encrypted_*" -exec rm -fv {} +

      #     printf '${EMAIL_ADDRESS}\n' | sh -c "${cmd}" -- \
      #       init --apply --purge-binary --force --no-tty --source-path $GITHUB_WORKSPACE
